In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("C:/Users/vidhy/OneDrive/Pictures/Documents/Chocolate Sales (2).csv")
df

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184
...,...,...,...,...,...,...
3277,Karlen McCaffrey,Australia,Spicy Special Slims,17/05/2024,"$5,303.58",354
3278,Jehu Rudeforth,USA,White Choc,07/06/2024,"$7,339.32",121
3279,Ches Bonnell,Canada,Organic Choco Syrup,26/07/2024,$616.09,238
3280,Dotty Strutley,India,Eclairs,28/07/2024,"$2,504.62",397


In [3]:
df.shape

(3282, 6)

In [4]:
df.columns

Index(['Sales Person', 'Country', 'Product', 'Date', 'Amount',
       'Boxes Shipped'],
      dtype='object')

In [5]:
df.dtypes

Sales Person     object
Country          object
Product          object
Date             object
Amount           object
Boxes Shipped     int64
dtype: object

In [6]:
df.isna().sum()

Sales Person     0
Country          0
Product          0
Date             0
Amount           0
Boxes Shipped    0
dtype: int64

In [7]:
df.drop(['Date','Amount'],axis=1,inplace=True)
df

,Sales Person,Country,Product,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,180
1,Van Tuxwell,India,85% Dark Bars,94
2,Gigi Bohling,India,Peanut Butter Cubes,91
3,Jan Morforth,Australia,Peanut Butter Cubes,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,184
...,...,...,...,...
3277,Karlen McCaffrey,Australia,Spicy Special Slims,354
3278,Jehu Rudeforth,USA,White Choc,121
3279,Ches Bonnell,Canada,Organic Choco Syrup,238
3280,Dotty Strutley,India,Eclairs,397


In [8]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Sales Person']=lab.fit_transform(df['Sales Person'])
df['Country']=lab.fit_transform(df['Country'])
df['Product']=lab.fit_transform(df['Product'])




In [9]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[19,  3, 17],
       [14,  2,  1],
       [ 7,  1,  8],
       ...,
       [ 2,  4, 21],
       [16,  0,  5],
       [ 6,  3, 17]], shape=(2297, 3))

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [12]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([ 46, 100,  10,  46,  21,  46, 144,  21,   7,  51,  59, 100,  10,
         7,  54,  25,  46, 144, 144,  12,  95,  46,  11,  46,  12,  11,
        31,  12,  73,  54,   7,  10,  91,  80,  46,  54,  11,  46,  11,
        46,  46,  91,  46,  46,  51,  12, 133,  10,  95,  21,  14, 100,
       100, 100,  46,  73,   7,  51, 100,  10,  12, 100,  11,  21,  31,
       112,  12, 142,  11,  10,  10,  11,  46,  10, 142,  59,  46,  63,
        21,   7, 133,  51,  11, 133,  12, 100, 100,   7,  10,  24, 100,
        10,  18,  46, 100,  18,  95, 100,   7, 133,  31,  21,  14,  21,
        46,  51,  46,   7,  10,  12, 100,  12,  18,  10, 100,  11, 133,
        95,  11,   7, 142,  10,  10,  10,  51,  12,  18,  73,  24,  54,
        46,  18,  21,  46,  18, 100,  51,  46,  84,  46,  91,  46, 100,
        21,  10,  21, 100,  11,  46,  51,  11,  46, 100,  46, 142,  46,
        91, 144,  59, 133, 144,  71, 144, 133, 100,  12,  21,  95, 100,
        10,  46, 100,  18,  10,  91,  46,  12,  54, 100,  18,  4

In [13]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(364, 364))

In [14]:
score=accuracy_score(y_test,y_pred)*100
score

1.015228426395939

In [15]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         5
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         4
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         5
           7       0.02      0.25      0.04         4
           8       0.00      0.00      0.00         5
           9       0.00      0.00      0.00         1
          10       0.00      0.00      0.00         0
          11       0.04      0.33      0.06         6
          12       0.02      0.12      0.03         8
          13       0.00      0.00      0.00         1
          14       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         3
          16       0.00      0.00      0.00         3
          17       0.00      0.00      0.00         2
          18       0.00    

C:\Users\vidhy\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\vidhy\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\vidhy\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i